name: AWS Lambda deploy

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Move node_modules to dist
        run: mv node_modules dist/node_modules

      - name: Zip
        run: (cd dist && zip -r ../function.zip .)

      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          function_name: mfalcon-test
          runtime: nodejs16.x
          memory_size: 256
          timeout: 30
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
          zip_file: function.zip
          handler: index.handler
          role: arn:aws:iam::518968110740:role/service-role/mfalcon-test-role-hv4hgmtn
